using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Common;
using Model;
using System.Xml.Linq;
using System.IO;

namespace View
{
    public partial class UserListForm : Form
    {
        private BindingList<User> userList;

        private IService service;

        public UserListForm(IService service, IList<User> userList)
        {
            this.service = service;

            this.userList = new BindingList<User>(userList);

            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = this.userList /* TODO: Assign the real data here.*/;
        }

        private void button1_Click(object sender, EventArgs e)
        {
            int[] selectedRows = gridView1.GetSelectedRows();

            var row = gridView1.GetRow(selectedRows[0]);

            EditUserForm editUserForm = new EditUserForm(userList, (User)row);

            editUserForm.ShowDialog();
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void UserListForm_Activated(object sender, EventArgs e)
        {
            gridView1.UpdateCurrentRow();
        }

        private void saveXMLButton_Click(object sender, EventArgs e)
        {
            var xml = new XElement("Users", userList.Select(x => new XElement("User",
                new XAttribute("Id", x.Id),
                new XAttribute("UserName", x.Username),
                new XAttribute("Password", x.Password),
                new XAttribute("Familyname", x.FamilyName),
                new XAttribute("Firstname", x.FirstName),
                new XAttribute("Borndate", x.BornDate),
                new XAttribute("Bornplace", x.BornPlace),
                new XAttribute("City", x.ResidenceCity))));

            SaveFileDialog saveFileDialog1 = new SaveFileDialog();
            saveFileDialog1.Filter = "XML file|*.xml";
            saveFileDialog1.Title = "Save an XML File";
            saveFileDialog1.ShowDialog();

            if (saveFileDialog1.FileName != "")
            {
                using (StreamWriter sw = new StreamWriter(saveFileDialog1.OpenFile()))
                {
                    xml.Save(sw);
                    sw.Close();
                }
            }
        }
    }
}
